name: fhir_validation
description: A Dart/Flutter package for validating FHIR JSON.
version: 0.11.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_validation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  antlr4: ^4.13.1
  fhir_primitives: ^0.1.0
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_stu3:
    path: ../fhir_stu3
  fhir_r4:
    path: ../fhir_r4
  fhir_r5:
    path: ../fhir_r5
  collection: ^1.18.0
  crypto: ^3.0.3
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  petitparser: ^6.0.2
  riverpod_annotation: ^2.3.5
  ucum: ^0.4.0
  universal_html: ^2.2.4
  validators: ^3.0.0

dev_dependencies:
  ### ****** PUB.DEV ******
  # analyzer: ">=3.4.0 <=4.2.0"
  # analyzer: ^4.2.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  test: ^1.25.2
