name: fhir_validation
description: A Dart/Flutter package for validating FHIR JSON.
version: 0.11.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_validation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  fhir_definitions: 
    path: ../fhir_definitions
  fhir_r4:
    path: ../fhir_r4
  flutter_test:
    sdk: flutter
  grapheme_splitter: ^1.0.1
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8

  mocktail: ^1.0.4
  # test: ^1.25.8
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - lib/test/test1/
    - lib/test/test2/
